name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [6.0.405]
        node: [18]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Cache Packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('paket.lock') }}
      - name: Run build
        run: dotnet run build
      - name: Run test
        run: dotnet run test
      - name: Bundle releases
        run: dotnet run publish
      # For now I simply make a continuous build
      - name: Delete old release
        run: gh release delete canary -y --cleanup-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release files
        uses: ncipollo/release-action@v1
        with:
          artifacts: "publish/*.tar.lz"
          generateReleaseNotes: true
          name: Continuous Build
          prerelease: true
          tag: canary
